#!/bin/bash

if [ -d "$HOME/.dbus/session-bus" ]; then
	cd "$HOME/.dbus/session-bus"
	for i in $(ls); do
		export $(cat "$i" | grep DBUS_SESSION_BUS_ADDRESS=)
	done
elif [ -r "$HOME/.dbus/Xdbus" ]; then
	. "$HOME/.dbus/Xdbus"
fi

outline=$(acpi -b)
percen=$(echo "$outline" | sed 's/.*,\s\([0-9]*\)%.*/\1/')

if [ $(echo "$outline" | grep Discharging | wc -l) -eq 1 ]; then 
	if [ "$percen" -lt 25 ]; then
		notify-send --urgency=CRITICAL 'BATTERY IS LOW; DO SOMETHING NOW'
	fi
	exit 0
elif [ $(echo "$outline" | grep Charging | wc -l) -eq 1 ]; then 
	if [ "$percen" -gt 95 ]; then
		notify-send --urgency=CRITICAL 'BATTERY IS CHARGED; RRAAHHH'
	fi
	exit 0
elif [ $(acpi -b | grep -i FULL | wc -l) -eq 1 ]; then 
	#notify-send --urgency=CRITICAL 'BATTERY IS CHARGED; RRAAHHH'
	exit 0
fi
