#!/bin/bash
conky -c ~/.conky/.conkyrc_proc &
conky -c ~/.conky/.conkyrc_top &
#conky -c ~/.conky/.conkyrc_todo &
conky -c ~/.conky/.conkyrc_network &
conky -c ~/.conky/.conkyrc_netstat &
conky -c ~/.conky/.conkyrc_taka
