#!/bin/bash

CONFIG_DIR='/home/neil/.config/spotify/Users'
PREF='prefs'

killall spotify

for i in $(ls ~/.config/spotify/Users); do
    echo "ui.track_notifications_enabled=false" >> "$CONFIG_DIR/$i/$PREF"
done

