#!/bin/bash

repoDir='/home/neil/dotfiles/'
cd "$repoDir"

status=$(git status -uno)
echo "$status" | grep -i 'up-to-date' &> /dev/null

if (( $? != 0 )); then
	blurb=$(git pull)

	echo "$blurb" | grep -i error
	E="$?"
	echo "$blurb" | grep -i fatal
	F="$?"

	if (( $E == 0 )) || (( $F ==0 )); then
		echo "$blurb"
		notify-send 'Failed to pull updates to dotfiles'
	else
		notify-send 'Pulled updates to dotfiles'
	fi
fi
