#!/bin/bash

repoDir='/home/neil/dotfiles/'
cd "$repoDir"

LOCAL=$(git rev-parse @{0})
REMOTE=$(git rev-parse @{u})
BASE=$(git merge-base @ @{u})

if [ $LOCAL = $REMOTE ]; then
	echo "Up-to-date" &> /dev/null
elif [ $LOCAL = $BASE ]; then
	echo "Need to pull" &> /dev/null

	blurb=$(git pull)

	echo "$blurb" | grep -i error
	E="$?"
	echo "$blurb" | grep -i fatal
	F="$?"

	if (( $E == 0 )) || (( $F ==0 )); then
		echo "$blurb"
		notify-send 'Failed to pull updates to dotfiles'
	else
		notify-send 'Pulled updates to dotfiles'
	fi
elif [ $REMOTE = $BASE ]; then
	echo "Need to push" &> /dev/null
else
	echo "Diverged" &> /dev/null
fi
