#!/bin/bash

if [ "$(pidof spotify)" ]; then
	./sp "$1"
elif [ "$(pidof mocp)" ]; then
	if [ "$1" == "play" ] || [ "$1" == "pause" ]; then
		mocp -G
	elif [ "$1" == "next" ]; then
		mocp --next
	elif [ "$1" == "prev" ]; then
		mocp --previous
	fi
elif [ "$(pidof mpd)" ]; then
	if [ "$1" == "play" ]; then
		mpc toggle
		mpc -p 6678 toggle
	else
		mpc "$1"
		mpc -p 6678 "$1"
	fi
fi
