#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 {update|noupgrade|stat}"
	exit 2
fi

statFile="/dev/shm/apt.stat"

if [ "$1" == "stat" ]; then
	if [ -e "$statFile" ]; then
		awk -F';' '{print $1}' "$statFile"
	fi
	exit 0
fi

me=$(id -u)

if (( me != 0 )); then
	echo "You need to be root in order to to this"
	exit 1
fi

if [ "$1" == "update" ]; then
	apt-get update &> /dev/null
elif [ "$1" == "noupgrade" ]; then
	out=$(apt-get upgrade --assume-no 2> /dev/null)
	echo "$out" | grep 'upgraded,' | sed 's/^\([0-9][0-9]*\)\supgraded.*/\1/' > "$statFile"
	check=$(cat "$statFile")
	if [ -z "$check" ]; then
		echo "-1" > "$statFile"
	fi
else
	echo "Usage: $0 {update|noupgrade}"
	exit 3
fi

chmod 777 "$statFile"
exit 0
