#!/bin/bash

volume=''

for i in $(amixer get Master | grep -o "\[.*%\]" | sed -e 's/\[//' -e 's/\]//'); do
	if [ "x$volume" != "x" ]; then
		if [ "x$volume" != "x$i" ]; then
			volume="$volume $i"
		fi
	else
		volume="$i"
	fi
done

echo "$volume"
