#!/bin/bash

blurb=$(acpi -b)
status=$(echo "$blurb" | awk '{print $3}' | sed -e 's/.$//')
percen=$(echo "$blurb" | awk '{print $4}' | sed -e 's/,//')

if [[ "${status}" = "Full" ]]; then
	echo "bat: $percen"
elif [[ "${status}" = "Charging" ]]; then
	echo "chr: $percen"
elif [[ "${status}" = "Discharging" ]]; then
	echo "bat: $percen"
elif [[ "${status}" = "Unknown" ]]; then
	echo "unk: $percen"
else
	echo "$status $percen"
fi
