#!/bin/bash

blurb=$(acpi -b)
status=$(echo "$blurb" | awk '{print $3}' | sed -e 's/.$//')
percen=$(echo "$blurb" | awk '{print $4}' | sed -e 's/,//')

if [ "x$status" == "xFull" ]; then
	echo "FULL"
elif [ "x$status" == "xCharging" ]; then
	echo "CHR $percen"
elif [ "x$status" == "xDischarging" ]; then
	echo "BAT $percen"
elif [ "x$status" == "xUnknown" ]; then
	echo "UNK $percen"
else
	echo "$status $percen"
fi
