#!/usr/bin/env python

import os
#needed = ["sda1", "sda6", "sda7"]
needed = ["sd"]

df_output = [s.split() for s in os.popen("df -h").read().splitlines()]
#print df_output

for x in df_output:
	if any(y in x[0] for y in needed):
		print "/" + x[5].rsplit('/', 1)[1] + ": " +  x[3] + ", ",
