#!/bin/bash

wget --spider https://icanhazip.com/ &> /dev/null
if (( $? != 0 )); then
    echo "Kein Internetverbindung" > /dev/shm/icanhazip.out
else
    curl -s -4 https://icanhazip.com/ &> /dev/shm/icanhazip.out
fi
