#!/bin/bash

if [ "$(pidof spotify)" ]; then
	blurb="$(./sp current-conky)"
	echo "SPOTIFY: $blurb"
elif [ "$(pidof mocp)" ] && [ "$(mocp -Q %state)" == "PLAY" ]; then
	artist="$(mocp -Q %artist)"
	song="$(mocp -Q %song)"
	echo "MOCP: $artist $song"
elif [ "$(pidof mpd)" ]; then
	blurb="$(mpc -p 6678 current)"
	echo "MPD: $blurb"
fi
