#!/bin/bash

blurb=$(acpi -b)
status=$(echo "$blurb" | awk '{print $3}' | sed -e 's/.$//')
percen=$(echo "$blurb" | awk '{print $4}' | sed -e 's/,//')
displayStatus=""

if [ "x$status" == "xFull" ]; then
	displayStatus="FULL"
elif [ "x$status" == "xCharging" ]; then
	displayStatus="CHR"
elif [ "x$status" == "xDischarging" ]; then
	displayStatus="BAT"
elif [ "x$status" == "xUnknown" ]; then
	displayStatus="UNK"
else
	displayStatus="$status"
fi

echo "$displayStatus $percen"
