#!/bin/bash

volume=''

for i in $(amixer get Master | grep -o "\[.*%\]" | sed -e 's/\[//' -e 's/\]//'); do
	if [ "x$volume" != "x" ]; then
		volume="$volume $i"
	else
		volume="$i"
	fi
done

echo "$volume"
