#!/bin/bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
	. "$HOME/.dbus/Xdbus"
fi

if [ $(acpi -b | grep Discharging | sed 's/.*Discharging,\s\([0-9]*\)%.*/\1/') -lt 25 ]; then 
	notify-send --urgency=CRITICAL 'BATTERY IS LOW; DO SOMETHING NOW'
	exit 0
elif [ $(acpi -b | grep Charging | sed 's/.*Charging,\s\([0-9]*\)%.*/\1/') -gt 95 ]; then 
	notify-send --urgency=CRITICAL 'BATTERY IS CHARGED; RRAAHHH'
	exit 0
elif [ $(acpi -b | grep -i FULL | wc -l) -eq 1 ]; then 
	notify-send --urgency=CRITICAL 'BATTERY IS CHARGED; RRAAHHH'
	exit 0
fi
