#!/bin/bash

sink=1

for i in $(pactl list sinks | sed -e 's/\s//g' | grep -i 'state'); do
	echo "$i" | grep -i 'running' > /dev/null
	if [ "$?" -eq 0 ]; then
		break
	fi
	sink=$(echo "$sink+1" | bc -l)
done

for i in $(pactl list sinks | sed -e 's/\s//g' | grep -i 'volume' | grep -i 'front'); do
	sink=$(echo "$sink-1" | bc -l)
	if [ "$sink" -eq 0 ]; then
		echo "$i" | sed -e 's/.*\/\([0-9]*\)%.*/\1%/'
	fi
done
