#!/bin/bash

if [ "$(mount | grep Scratch | wc -l)" == "0" ]; then
	echo 'MOUNT SCRATCH!'
	exit 5;
fi

killall deluged

daemon_port=$(sudo ~/dotfiles/assign_pia_port.sh 2> /dev/null)
echo "daemon port: $daemon_port" > /tmp/deluge-conf

listen_port=$(sudo ~/dotfiles/assign_pia_port.sh 2> /dev/null)
echo "listen port: $listen_port" >> /tmp/deluge-conf

web_ui_port=$(sudo ~/dotfiles/assign_pia_port.sh 2> /dev/null)
echo "web ui port: $web_ui_port" >> /tmp/deluge-conf

tempcore=$(mktemp)
echo "tempcore: $tempcore"

tempwebui=$(mktemp)
echo "tempwebui: $tempwebui"

temphostconf=$(mktemp)
echo "temphostconf: $temphostconf"

jq ".listen_ports=[$listen_port, $listen_port] | .daemon_port=$daemon_port"  ~/.config/deluge/core.conf > $tempcore
jq ".port=$web_ui_port" ~/.config/deluge/web_plugin.conf > $tempwebui
jq ".hosts[0][2]=$daemon_port" ~/.config/deluge/hostlist.conf.1.2 > $temphostconf

mv $tempcore ~/.config/deluge/core.conf
mv $tempwebui ~/.config/deluge/web_plugin.conf
mv $temphostconf ~/.config/deluge/hostlist.conf.1.2

deluged && deluge &
